"""Initial BioMed action catalog — deterministic, human validation required."""

from __future__ import annotations

from typing import Any

ACTION_LIBRARY: dict[str, dict[str, Any]] = {
    "ACT-ERG-001": {
        "nome": "avaliação ergonômica",
        "quando_usar": ["alta_severidade_osteomuscular", "cid_grupo_M"],
        "dados_minimos": ["eventos", "dias_perdidos", "grupos_cid"],
        "responsavel_sugerido": "SST/ergonomia",
        "indicador": "dias_perdidos;duracao_media",
        "evidencia_esperada": "redução de duração média em 90 dias",
        "limitacoes": ["não isola causa única"],
        "contraindicacoes": ["dados_iqb_critico"],
        "validacao_humana": True,
    },
    "ACT-ERG-002": {
        "nome": "análise de posto",
        "quando_usar": ["concentracao_setorial", "alta_severidade_osteomuscular"],
        "dados_minimos": ["setores_criticos"],
        "responsavel_sugerido": "engenharia/SST",
        "indicador": "eventos_por_setor",
        "evidencia_esperada": "queda de eventos no posto priorizado",
        "limitacoes": ["exige visita técnica"],
        "contraindicacoes": [],
        "validacao_humana": True,
    },
    "ACT-RET-001": {
        "nome": "acompanhamento de recorrentes",
        "quando_usar": ["alta_recorrencia"],
        "dados_minimos": ["recorrencia"],
        "responsavel_sugerido": "BioMed",
        "indicador": "recorrencia",
        "evidencia_esperada": "redução de reincidência",
        "limitacoes": ["identidade aproximada"],
        "contraindicacoes": [],
        "validacao_humana": True,
    },
    "ACT-RET-002": {
        "nome": "retorno ao trabalho",
        "quando_usar": ["alta_recorrencia", "afastamentos_longos"],
        "dados_minimos": ["afastamentos_longos"],
        "responsavel_sugerido": "RH/BioMed",
        "indicador": "afastamentos_longos",
        "evidencia_esperada": "retorno sustentado",
        "limitacoes": ["não substitui avaliação clínica"],
        "contraindicacoes": [],
        "validacao_humana": True,
    },
    "ACT-JOR-001": {
        "nome": "revisão de jornada",
        "quando_usar": ["alta_frequencia", "horas_elevadas"],
        "dados_minimos": ["frequencia", "horas_perdidas_registradas"],
        "responsavel_sugerido": "RH/liderança",
        "indicador": "frequencia",
        "evidencia_esperada": "estabilização da frequência",
        "limitacoes": ["depende de decisão empresarial"],
        "contraindicacoes": [],
        "validacao_humana": True,
    },
    "ACT-RESP-001": {
        "nome": "campanha respiratória",
        "quando_usar": ["aumento_respiratorio"],
        "dados_minimos": ["grupos_cid"],
        "responsavel_sugerido": "BioMed",
        "indicador": "eventos_cid_J",
        "evidencia_esperada": "atenção à sazonalidade",
        "limitacoes": ["sazonalidade confunde atribuição"],
        "contraindicacoes": [],
        "validacao_humana": True,
    },
    "ACT-RESP-002": {
        "nome": "vacinação",
        "quando_usar": ["aumento_respiratorio"],
        "dados_minimos": ["grupos_cid"],
        "responsavel_sugerido": "SESMT/BioMed",
        "indicador": "eventos_cid_J",
        "evidencia_esperada": "cobertura vacinal",
        "limitacoes": ["adesão voluntária"],
        "contraindicacoes": [],
        "validacao_humana": True,
    },
    "ACT-AMB-001": {
        "nome": "avaliação de ambiente",
        "quando_usar": ["aumento_respiratorio", "aumento_acidentes"],
        "dados_minimos": ["setores_criticos"],
        "responsavel_sugerido": "SST",
        "indicador": "eventos_por_setor",
        "evidencia_esperada": "plano ambiental",
        "limitacoes": [],
        "contraindicacoes": [],
        "validacao_humana": True,
    },
    "ACT-SEG-001": {
        "nome": "análise de acidentes",
        "quando_usar": ["aumento_acidentes"],
        "dados_minimos": ["eventos", "setores_criticos"],
        "responsavel_sugerido": "SST",
        "indicador": "eventos",
        "evidencia_esperada": "investigação documentada",
        "limitacoes": [],
        "contraindicacoes": [],
        "validacao_humana": True,
    },
    "ACT-SEG-002": {
        "nome": "treinamento de liderança",
        "quando_usar": ["aumento_acidentes", "alta_frequencia"],
        "dados_minimos": ["frequencia"],
        "responsavel_sugerido": "RH",
        "indicador": "frequencia",
        "evidencia_esperada": "adesão de lideranças",
        "limitacoes": [],
        "contraindicacoes": [],
        "validacao_humana": True,
    },
    "ACT-SEG-003": {
        "nome": "revisão de processo",
        "quando_usar": ["aumento_acidentes", "concentracao_setorial"],
        "dados_minimos": ["setores_criticos"],
        "responsavel_sugerido": "operações/SST",
        "indicador": "eventos_por_setor",
        "evidencia_esperada": "mudança de processo registrada",
        "limitacoes": [],
        "contraindicacoes": [],
        "validacao_humana": True,
    },
    "ACT-LONG-001": {
        "nome": "acompanhamento de longos afastamentos",
        "quando_usar": ["afastamentos_longos"],
        "dados_minimos": ["afastamentos_longos"],
        "responsavel_sugerido": "BioMed/RH",
        "indicador": "afastamentos_longos",
        "evidencia_esperada": "plano de retorno",
        "limitacoes": [],
        "contraindicacoes": [],
        "validacao_humana": True,
    },
    "ACT-SM-001": {
        "nome": "ação de saúde mental organizacional",
        "quando_usar": ["aumento_saude_mental"],
        "dados_minimos": ["grupos_cid"],
        "responsavel_sugerido": "RH/BioMed",
        "indicador": "eventos_cid_F",
        "evidencia_esperada": "ações coletivas sem PII",
        "limitacoes": ["sem dado clínico individual"],
        "contraindicacoes": ["proibido_texto_clinico"],
        "validacao_humana": True,
    },
    "ACT-COV-001": {
        "nome": "revisão de cobertura assistencial",
        "quando_usar": ["baixa_cobertura"],
        "dados_minimos": ["cobertura_assistencial"],
        "responsavel_sugerido": "BioMed/gestão",
        "indicador": "cobertura_assistencial",
        "evidencia_esperada": "aumento de comparecimento",
        "limitacoes": [],
        "contraindicacoes": [],
        "validacao_humana": True,
    },
    "ACT-QUAL-001": {
        "nome": "melhoria da qualidade da base",
        "quando_usar": ["iqb_baixo"],
        "dados_minimos": ["iqb"],
        "responsavel_sugerido": "gestão de dados/RH",
        "indicador": "iqb",
        "evidencia_esperada": "IQB acima do limiar",
        "limitacoes": [],
        "contraindicacoes": [],
        "validacao_humana": True,
    },
}


def list_actions() -> list[dict[str, Any]]:
    return [{"id": k, **v} for k, v in ACTION_LIBRARY.items()]


def get_action(action_id: str) -> dict[str, Any] | None:
    item = ACTION_LIBRARY.get(action_id)
    if not item:
        return None
    return {"id": action_id, **item}
